Dataset:
  train_data_path: ""
  image_size: [384, 256]
  channels: 3
Train:
  batch_size: 4
  epochs: 10
  optimizer: "adam"
  learning_rate: 0.001
  pretrained: ""
  device: 0
  architecture: "resnet50"
Logging:
  tb_logdir: "logs"
  ckpt_dir: ""