Dataset:
  train_data_path: "../json_files/new_train.json"
  val_data_path: "../json_files/new_val.json"
  image_size: [1024, 320]
  channels: 3
Train:
  batch_size: 2
  epochs: 50
  evals_per_epoch: 2
  optimizer: "adam"
  lr_scheduler:
    lr_init: 0.0001
    StepDecay:
      use: True
      lr_end: 0.0000001
      epoch_steps: [ 15, 25, 35 ]
  pretrained: ""
  device: 0
  architecture: "resnet50"
  augmentation:
    HorizonalFlip:
      p: 0.5
    RandomBrightness:
      p: 0.0
      low_value: 0.6
      high_value: 1.2
    RandomGamma:
      p: 0.0
      low_value: 0.9
      high_value: 1.1
Loss:
  appearance_matching_loss_weight: 0.85
  smoothness_loss_weight: 1.0
  lr_consistency_loss_weight: 1.0
Logging:
  tb_logdir: "/home/milojkon/Datasets/depth/train_logs/27_05_2021_1024_320/logs"
  ckpt_dir: "/home/milojkon/Datasets/depth/train_logs/27_05_2021_1024_320/checkpoints"
