Dataset:
  train_data_path: "../json_files/train.json"
  val_data_path: "../json_files/val.json"
  image_size: [1280, 320]
  channels: 3
Train:
  batch_size: 4
  epochs: 10
  evals_per_epoch: 2
  optimizer: "adam"
  lr_scheduler:
    lr_init: 0.0001
    StepDecay:
      use: True
      lr_end: 0.00001
      epoch_steps: [ 1, 3, 5 ]
  pretrained: "/home/milojkon/Datasets/depth/train_logs/18_04_2020/checkpoints/10_4239.pt"
  device: 0
  architecture: "resnet50"
  augmentation:
    HorizonalFlip:
      p: 0.5
    RandomBrightness:
      p: 1
      low_value: 0.6
      high_value: 1.2
    RandomGamma:
      p: 1
      low_value: 0.9
      high_value: 1.1
Logging:
  tb_logdir: "/home/milojkon/Datasets/depth/train_logs/20_04_2020/logs_2"
  ckpt_dir: "/home/milojkon/Datasets/depth/train_logs/20_04_2020/checkpoints_2"
